version: "2"
services:
  web:
    env_file:
      - /srv/webapp/.env.prod
    volumes:
      - /srv/webapp/services/gunicorn:/var/log/gunicorn
  db:
    env_file:
      - /srv/webapp/.env.prod
    volumes:
      - db_data:/data
  nginx:
    ports:
      - "80:80"
    volumes:
      - /srv/webapp/services/nginx:/var/log/nginx
