version: "2"
services:
  web:
    build:
      context: .
      dockerfile: webapp.dockerfile
    depends_on:
      - db
    command: gunicorn --config gunicorn_config.py app:app
  db:
    build:
      context: .
      dockerfile: mongodb.dockerfile
    command: mongod --config /etc/mongod.conf
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    depends_on:
      - web