version: "2"
services:
  web:
    env_file:
      - /srv/webapp/.env.prod
    volumes:
      - /srv/webapp/services/gunicorn:/var/log/gunicorn
    command: gunicorn --config gunicorn_config.py app:app
  db:
    env_file:
      - /srv/webapp/.env.prod
    volumes:
      - db_data:/data
  nginx:
    ports:
      - "80:80"
    volumes:
      - nginx_logs:/var
volumes:
  db_data:
    driver: local
  nginx_logs:
    driver: local