version: "2"
services:
  web:
    ports:
      - "80:8000"
    env_file:
      - /srv/webapp/.env.prod
    volumes:
      - /srv/webapp/services/gunicorn:/var/log/gunicorn
    command: gunicorn --config gunicorn_config.py app:app
  db:
    env_file:
      - /srv/webapp/.env.prod
    volumes:
      - db_data:/data

volumes:
  db_data:
    driver: local